# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1021, 780)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.original_img_label = QtWidgets.QLabel(self.groupBox)
        self.original_img_label.setAlignment(QtCore.Qt.AlignCenter)
        self.original_img_label.setObjectName("original_img_label")
        self.verticalLayout_4.addWidget(self.original_img_label)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.preview_img_label = QtWidgets.QLabel(self.groupBox_2)
        self.preview_img_label.setAlignment(QtCore.Qt.AlignCenter)
        self.preview_img_label.setObjectName("preview_img_label")
        self.verticalLayout_5.addWidget(self.preview_img_label)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.image_deconvolution_frame = QtWidgets.QFrame(self.centralwidget)
        self.image_deconvolution_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.image_deconvolution_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.image_deconvolution_frame.setObjectName("image_deconvolution_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.image_deconvolution_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.id_label = QtWidgets.QLabel(self.image_deconvolution_frame)
        self.id_label.setObjectName("id_label")
        self.verticalLayout_2.addWidget(self.id_label)
        self.id_method_cb = QtWidgets.QComboBox(self.image_deconvolution_frame)
        self.id_method_cb.setObjectName("id_method_cb")
        self.id_method_cb.addItem("")
        self.id_method_cb.addItem("")
        self.verticalLayout_2.addWidget(self.id_method_cb)
        self.id_button = QtWidgets.QPushButton(self.image_deconvolution_frame)
        self.id_button.setObjectName("id_button")
        self.verticalLayout_2.addWidget(self.id_button)
        self.gridLayout.addWidget(self.image_deconvolution_frame, 0, 1, 1, 1)
        self.noise_canceling_frame = QtWidgets.QFrame(self.centralwidget)
        self.noise_canceling_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.noise_canceling_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.noise_canceling_frame.setObjectName("noise_canceling_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.noise_canceling_frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.nc_label = QtWidgets.QLabel(self.noise_canceling_frame)
        self.nc_label.setObjectName("nc_label")
        self.verticalLayout_3.addWidget(self.nc_label)
        self.nc_method_cb = QtWidgets.QComboBox(self.noise_canceling_frame)
        self.nc_method_cb.setObjectName("nc_method_cb")
        self.nc_method_cb.addItem("")
        self.nc_method_cb.addItem("")
        self.nc_method_cb.addItem("")
        self.verticalLayout_3.addWidget(self.nc_method_cb)
        self.nc_footprint_cb = QtWidgets.QComboBox(self.noise_canceling_frame)
        self.nc_footprint_cb.setObjectName("nc_footprint_cb")
        self.nc_footprint_cb.addItem("")
        self.nc_footprint_cb.addItem("")
        self.nc_footprint_cb.addItem("")
        self.nc_footprint_cb.addItem("")
        self.nc_footprint_cb.addItem("")
        self.nc_footprint_cb.addItem("")
        self.verticalLayout_3.addWidget(self.nc_footprint_cb)
        self.nc_button = QtWidgets.QPushButton(self.noise_canceling_frame)
        self.nc_button.setObjectName("nc_button")
        self.verticalLayout_3.addWidget(self.nc_button)
        self.gridLayout.addWidget(self.noise_canceling_frame, 0, 0, 1, 1)
        self.upscaling_frame = QtWidgets.QFrame(self.centralwidget)
        self.upscaling_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.upscaling_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.upscaling_frame.setObjectName("upscaling_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.upscaling_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.us_label = QtWidgets.QLabel(self.upscaling_frame)
        self.us_label.setObjectName("us_label")
        self.verticalLayout.addWidget(self.us_label)
        self.us_method_cb = QtWidgets.QComboBox(self.upscaling_frame)
        self.us_method_cb.setObjectName("us_method_cb")
        self.us_method_cb.addItem("")
        self.us_method_cb.addItem("")
        self.us_method_cb.addItem("")
        self.us_method_cb.addItem("")
        self.us_method_cb.addItem("")
        self.us_method_cb.addItem("")
        self.us_method_cb.addItem("")
        self.us_method_cb.addItem("")
        self.us_method_cb.addItem("")
        self.us_method_cb.addItem("")
        self.us_method_cb.addItem("")
        self.us_method_cb.addItem("")
        self.verticalLayout.addWidget(self.us_method_cb)
        self.us_button = QtWidgets.QPushButton(self.upscaling_frame)
        self.us_button.setObjectName("us_button")
        self.verticalLayout.addWidget(self.us_button)
        self.gridLayout.addWidget(self.upscaling_frame, 0, 2, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1021, 22))
        self.menubar.setAutoFillBackground(False)
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuExamples = QtWidgets.QMenu(self.menubar)
        self.menuExamples.setObjectName("menuExamples")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuAdd_Noise = QtWidgets.QMenu(self.menuTools)
        self.menuAdd_Noise.setObjectName("menuAdd_Noise")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionBlur_Image = QtWidgets.QAction(MainWindow)
        self.actionBlur_Image.setObjectName("actionBlur_Image")
        self.actionGaussian = QtWidgets.QAction(MainWindow)
        self.actionGaussian.setObjectName("actionGaussian")
        self.actionLocalvar = QtWidgets.QAction(MainWindow)
        self.actionLocalvar.setObjectName("actionLocalvar")
        self.actionPoisson = QtWidgets.QAction(MainWindow)
        self.actionPoisson.setObjectName("actionPoisson")
        self.actionSalt = QtWidgets.QAction(MainWindow)
        self.actionSalt.setObjectName("actionSalt")
        self.actionPepper = QtWidgets.QAction(MainWindow)
        self.actionPepper.setObjectName("actionPepper")
        self.actionS_P = QtWidgets.QAction(MainWindow)
        self.actionS_P.setObjectName("actionS_P")
        self.actionSpeckle = QtWidgets.QAction(MainWindow)
        self.actionSpeckle.setObjectName("actionSpeckle")
        self.actionSave_Path = QtWidgets.QAction(MainWindow)
        self.actionSave_Path.setObjectName("actionSave_Path")
        self.actionAbout_program = QtWidgets.QAction(MainWindow)
        self.actionAbout_program.setObjectName("actionAbout_program")
        self.actionAbout_creator = QtWidgets.QAction(MainWindow)
        self.actionAbout_creator.setObjectName("actionAbout_creator")
        self.actionAstronaut = QtWidgets.QAction(MainWindow)
        self.actionAstronaut.setObjectName("actionAstronaut")
        self.actionBrick = QtWidgets.QAction(MainWindow)
        self.actionBrick.setObjectName("actionBrick")
        self.actionCat = QtWidgets.QAction(MainWindow)
        self.actionCat.setObjectName("actionCat")
        self.actionCoins = QtWidgets.QAction(MainWindow)
        self.actionCoins.setObjectName("actionCoins")
        self.actionPSF = QtWidgets.QAction(MainWindow)
        self.actionPSF.setObjectName("actionPSF")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuExamples.addAction(self.actionAstronaut)
        self.menuExamples.addAction(self.actionBrick)
        self.menuExamples.addAction(self.actionCat)
        self.menuExamples.addAction(self.actionCoins)
        self.menuAbout.addAction(self.actionAbout_program)
        self.menuAbout.addAction(self.actionAbout_creator)
        self.menuAdd_Noise.addAction(self.actionGaussian)
        self.menuAdd_Noise.addAction(self.actionLocalvar)
        self.menuAdd_Noise.addAction(self.actionPoisson)
        self.menuAdd_Noise.addAction(self.actionSalt)
        self.menuAdd_Noise.addAction(self.actionPepper)
        self.menuAdd_Noise.addAction(self.actionS_P)
        self.menuAdd_Noise.addAction(self.actionSpeckle)
        self.menuTools.addAction(self.menuAdd_Noise.menuAction())
        self.menuTools.addAction(self.actionBlur_Image)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuExamples.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Image Betterificator"))
        self.groupBox.setTitle(_translate("MainWindow", "Original"))
        self.original_img_label.setText(_translate("MainWindow", "Image"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Preview"))
        self.preview_img_label.setText(_translate("MainWindow", "Image"))
        self.id_label.setText(_translate("MainWindow", "Image Deconvolution"))
        self.id_method_cb.setItemText(0, _translate("MainWindow", "Richardson-Lucy Method"))
        self.id_method_cb.setItemText(1, _translate("MainWindow", "Wiener Method"))
        self.id_button.setText(_translate("MainWindow", "Apply"))
        self.nc_label.setText(_translate("MainWindow", "Noise Canceling"))
        self.nc_method_cb.setItemText(0, _translate("MainWindow", "Mean"))
        self.nc_method_cb.setItemText(1, _translate("MainWindow", "Median"))
        self.nc_method_cb.setItemText(2, _translate("MainWindow", "Bilateral"))
        self.nc_footprint_cb.setItemText(0, _translate("MainWindow", "Disk 1"))
        self.nc_footprint_cb.setItemText(1, _translate("MainWindow", "Disk 5"))
        self.nc_footprint_cb.setItemText(2, _translate("MainWindow", "Disk 10"))
        self.nc_footprint_cb.setItemText(3, _translate("MainWindow", "Square 3"))
        self.nc_footprint_cb.setItemText(4, _translate("MainWindow", "Square 5"))
        self.nc_footprint_cb.setItemText(5, _translate("MainWindow", "Square 7"))
        self.nc_button.setText(_translate("MainWindow", "Apply"))
        self.us_label.setText(_translate("MainWindow", "Upscaling"))
        self.us_method_cb.setItemText(0, _translate("MainWindow", "ESPCN_x2"))
        self.us_method_cb.setItemText(1, _translate("MainWindow", "ESPCN_x3"))
        self.us_method_cb.setItemText(2, _translate("MainWindow", "ESPCN_x4"))
        self.us_method_cb.setItemText(3, _translate("MainWindow", "EDSR_x2"))
        self.us_method_cb.setItemText(4, _translate("MainWindow", "EDSR_x3"))
        self.us_method_cb.setItemText(5, _translate("MainWindow", "EDSR_x4"))
        self.us_method_cb.setItemText(6, _translate("MainWindow", "FSRCNN_x2"))
        self.us_method_cb.setItemText(7, _translate("MainWindow", "FSRCNN_x3"))
        self.us_method_cb.setItemText(8, _translate("MainWindow", "FSRCNN_x4"))
        self.us_method_cb.setItemText(9, _translate("MainWindow", "LapSRN_x2"))
        self.us_method_cb.setItemText(10, _translate("MainWindow", "LapSRN_x4"))
        self.us_method_cb.setItemText(11, _translate("MainWindow", "LapSRN_x8"))
        self.us_button.setText(_translate("MainWindow", "Apply"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuExamples.setTitle(_translate("MainWindow", "Examples"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.menuAdd_Noise.setTitle(_translate("MainWindow", "Add Noise"))
        self.actionOpen.setText(_translate("MainWindow", "Open ..."))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionBlur_Image.setText(_translate("MainWindow", "Blur Image"))
        self.actionGaussian.setText(_translate("MainWindow", "Gaussian"))
        self.actionLocalvar.setText(_translate("MainWindow", "Localvar"))
        self.actionPoisson.setText(_translate("MainWindow", "Poisson"))
        self.actionSalt.setText(_translate("MainWindow", "Salt"))
        self.actionPepper.setText(_translate("MainWindow", "Pepper"))
        self.actionS_P.setText(_translate("MainWindow", "Salt and Pepper"))
        self.actionSpeckle.setText(_translate("MainWindow", "Speckle"))
        self.actionSave_Path.setText(_translate("MainWindow", "Save Path"))
        self.actionAbout_program.setText(_translate("MainWindow", "About program"))
        self.actionAbout_creator.setText(_translate("MainWindow", "About creator"))
        self.actionAstronaut.setText(_translate("MainWindow", "Astronaut"))
        self.actionBrick.setText(_translate("MainWindow", "Brick"))
        self.actionCat.setText(_translate("MainWindow", "Cat"))
        self.actionCoins.setText(_translate("MainWindow", "Coins"))
        self.actionPSF.setText(_translate("MainWindow", "PSF"))
